### ISSUE TITLE
Too colourful?

### ISSUE THREAD

**Issue by FabioAntunes** [RRethy/nvim-base16#9]
I'm finding these templates a bit too colourful if we compare them to the original ones. Cycling through the various templates I noticed that neutral colours such as white are not very commonly used.

Take base16-nord for example:

In http://chriskempson.com/projects/base16/
![Screenshot 2021-06-10 at 17 40 36](https://user-images.githubusercontent.com/2544673/121564084-fb57f600-ca12-11eb-87ee-bc48c8620d50.png)

In vim with vim-base16:
![Screenshot 2021-06-10 at 17 41 29](https://user-images.githubusercontent.com/2544673/121564196-19255b00-ca13-11eb-8e79-0d655c86e35f.png)

In nvim  with nvim-base16 with treesitter turned off:
![Screenshot 2021-06-10 at 17 42 34](https://user-images.githubusercontent.com/2544673/121564331-3f4afb00-ca13-11eb-8c2f-39e0ef0c1586.png)

In nvim  with nvim-base16 with treesitter turned on:
![Screenshot 2021-06-10 at 17 43 13](https://user-images.githubusercontent.com/2544673/121564419-5689e880-ca13-11eb-97d7-9a85aec91ef5.png)

And this is pretty much the same with all the schemes

**Comment by RRethy** [comment]
There's a few things going on here.

First for the regular non-treesitter highlights, most of the highlight groups are the same, but there was a few places where I diverged from vim-base16 such as the string in your screenshot (I would argue green strings is more correct than red based on [styling guidelines](https://github.com/chriskempson/base16/blob/master/styling.md)), line number column, and a few other places. That being said, when I get the chance I'll go back through the normal highlight groups since I may have diverged a bit too much since I focused on following the styling guidelines than following the other base16 repos.

Second, the treesitter highlights had no guide so again I focused on [styling guidelines](https://github.com/chriskempson/base16/blob/master/styling.md) which is quite vague. For example, the html tag in vim-base16 uses base05 while I use base0A for `TSTag`, it's not clear which colour should be used (it could also be base08). Again, when i get the chance I'll take a look through to see if I can get things closer to the guidelines.

Third, you won't see much *normal* colour when using treesitter, everything is a node in the syntax tree.
